### PR TITLE
React to PDF multi page support.

### PR DESCRIPTION
**Pull request by jshossen**
React to PDF multi page support.

### CODE REVIEW

**Review by MallikarjunHt — COMMENTED** [review]
no need to add extra `,` at the end react can understand its end of property. 

And for the pdf part its better to get html and rewrite in canvas rather than taking photo.
if we take photo we cannot resize without comprimising with clarith of pdf.

**Comment by MallikarjunHt** [comment]
> no need to add extra `,` at the end react can understand its end of property.
> 
> And for the pdf part its better to get html and rewrite in canvas rather than taking photo.
> if we take photo we cannot resize without comprimising with clarith of pdf.

just my suggetipon.

**Comment by jshossen** [comment]
But the main concept of react to pdf is taking photo and make it PDF.

**Comment by ivmarcos** [comment]
Nice work and sorry the delay @jshossen @MallikarjunHt . I am wondering if we really need to pass the image width and height for this and just not using the internal values from `jsPdf` to avoid controlling this via props.

Could you test using this instead? 

const width = doc.internal.pageSize.getWidth();
const height = doc.internal.pageSize.getHeight();

**Comment by ivmarcos** [comment]
Closing due lack of response.

**Pull request closed without merging**
